### ISSUE TITLE
Logical error in token management

### ISSUE THREAD

**Issue by jpontois** [Project-Timer/BackTimer#12]
**Type** : Logical error
**Where** : src/utils/jwt.js
**Description** :
When providing a valid token with a non existent user, the function test a property from a undefined user.

**Comment by jpontois** [comment]
**First iteration : No token provided**
BackTimer-node | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
BackTimer-node |     at ServerResponse.setHeader (_http_outgoing.js:536:11)
BackTimer-node |     at ServerResponse.header (/home/node/app/node_modules/express/lib/response.js:771:10)
BackTimer-node |     at ServerResponse.send (/home/node/app/node_modules/express/lib/response.js:170:12)
BackTimer-node |     at ServerResponse.json (/home/node/app/node_modules/express/lib/response.js:267:15)
BackTimer-node |     at /home/node/app/src/controllers/userController.js:37:13
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/model.js:4876:16
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/model.js:4899:21
BackTimer-node |     at model.<anonymous> (/home/node/app/node_modules/mongoose/lib/model.js:495:7)
BackTimer-node |     at /home/node/app/node_modules/kareem/index.js:315:21
BackTimer-node |     at next (/home/node/app/node_modules/kareem/index.js:209:27)
BackTimer-node |     at /home/node/app/node_modules/kareem/index.js:182:9
BackTimer-node |     at /home/node/app/node_modules/kareem/index.js:507:38
BackTimer-node |     at processTicksAndRejections (internal/process/task_queues.js:75:11)
BackTimer-node | Emitted 'error' event on Function instance at:
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/model.js:4878:13
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
BackTimer-node |     [... lines matching original stack trace ...]
BackTimer-node |     at processTicksAndRejections (internal/process/task_queues.js:75:11) {
BackTimer-node |   code: 'ERR_HTTP_HEADERS_SENT'
BackTimer-node | }

**Comment by jpontois** [comment]
## Second iteration : Token provided
BackTimer-node | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
BackTimer-node |     at ServerResponse.setHeader (_http_outgoing.js:536:11)
BackTimer-node |     at ServerResponse.header (/home/node/app/node_modules/express/lib/response.js:771:10)
BackTimer-node |     at ServerResponse.send (/home/node/app/node_modules/express/lib/response.js:170:12)
BackTimer-node |     at ServerResponse.json (/home/node/app/node_modules/express/lib/response.js:267:15)
BackTimer-node |     at /home/node/app/src/controllers/userController.js:37:13
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/model.js:4876:16
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/model.js:4899:21
BackTimer-node |     at model.<anonymous> (/home/node/app/node_modules/mongoose/lib/model.js:495:7)
BackTimer-node |     at /home/node/app/node_modules/kareem/index.js:315:21
BackTimer-node |     at next (/home/node/app/node_modules/kareem/index.js:209:27)
BackTimer-node |     at /home/node/app/node_modules/kareem/index.js:182:9
BackTimer-node |     at /home/node/app/node_modules/kareem/index.js:507:38
BackTimer-node |     at processTicksAndRejections (internal/process/task_queues.js:75:11)
BackTimer-node | Emitted 'error' event on Function instance at:
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/model.js:4878:13
BackTimer-node |     at /home/node/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
BackTimer-node |     [... lines matching original stack trace ...]
BackTimer-node |     at processTicksAndRejections (internal/process/task_queues.js:75:11) {
BackTimer-node |   code: 'ERR_HTTP_HEADERS_SENT'
BackTimer-node | }
